% -------------------------------------------------------------------
%  Generated by MATLAB on 17-Jan-2021 19:19:49
%  MATLAB version: 9.1.0.441655 (R2016b)
% -------------------------------------------------------------------


if ~exist('Incidence','var')
    Incidence = false;
end
if ~exist('Difference','var')
    Difference = false;
end

warning('off','MATLAB:table:ModifiedVarnames')

% Loads Weekly Corona Data
tab = readtable('currentData.csv','ReadRowNames',1,'ReadVariableNames',1,'HeaderLines',0);
week = datetime(zeros(1,length(tab.Properties.VariableNames)),1,1);
for i =  1:length(tab.Properties.VariableNames)
    year_week = split(tab.Properties.VariableNames{i}(2:end),'_KW');
    week(i) = getFirstWeek(str2double(year_week(1)))+calweeks(str2double(year_week(2)))-days(1);
end

if Incidence
    tab_data = table2array(tab(1:end-1,:));
    tab_data(isnan(tab_data))=0;
    Age = tab.Altergruppe(1:end-1);
    population = AgeCount(Age);
    tab_data = tab_data./population*100000;
else
    tab_data = table2array(tab(2:end-1,:));
    tab_data(isnan(tab_data))=0;
    Age = tab.Altergruppe(2:end-1);
end

if Difference
    tab_data = tab_data(:,2:end)-tab_data(:,1:end-1);
    week = week(2:end);
end


% custom colors
cmap_colors = interp1(linspace(0,1,4),[17.6 66.7 17.6; 19.2 30.2 55.7; ...
    83.1 22 22 ; 83.1 62.7 22]/100,...
    linspace(0,1,length(Age)));
if Incidence
    cmap_colors(1,:)=[0 0 0];
end
cmap = cmap_colors;
clearvars i population tab year_week